### ISSUE TITLE
Перейти на git и переехать на github

### ISSUE THREAD

**Issue by unhandled-exception** [unhandled-exception/pf2#28]
Originally reported by: **Oleg Volchkov (Bitbucket: [ovolchkov](https://bitbucket.org/ovolchkov), GitHub: Unknown)**

----------------------------------------

Чтобы у народа не было криков, что мы замшелые и немодные? Идиотскую идеологию и интерфейс гита я готов пережить. :)

Стандартный импорт Гитхаба теряет русские буковки в комитах, но через https://github.com/frej/fast-export мне удалось корректно преобразовать репозитории и загрузить его на Гитхаб.

Останется перенести тикеты, но для этого тоже есть скрипты в инете.

Леша, что скажешь?

----------------------------------------
- Bitbucket: https://bitbucket.org/ovolchkov/pf2/issue/28

**Comment by unhandled-exception** [comment]
Вроде переехали. Ссылки с хешами побились, но это не проблема.

**Comment by gzzz** [comment]
Ну, посмотрим как оно пойдёт.

Может не понравится и вернёмся взад!

**Comment by gzzz** [comment]
Здесь переводы строк в комментариях просто работают и не требуют два пробела в конце, аминь!

**Comment by unhandled-exception** [comment]
Интерфейс тут приятнее. Если так и дальше пойдет, то раскошелюсь на 84 доллара в год за приватные репозитории. Гитлаб на виртуалке поднимать будет дороже.

**Comment by unhandled-exception** [comment]
* 4a6210a Добавил в README.md команду клонирования библиотеки.
* 2df5b29 Добавил в список классов ссылки на файлы.
* 6acbd4c Поправил README.md.

**Comment by unhandled-exception** [comment]
Команда для формирования списка комитов для Гитхаба:
`git config --global alias.ghlog 'log --format="* %h %s" --reverse'`
