### ISSUE TITLE
Новые имена для экшнов

### ISSUE THREAD

**Issue by unhandled-exception** [unhandled-exception/pf2#33]
Алексей заметил, что Парсер может использовать в именах методов всякие слешики и скобочки. Поэтому можно уйти от `@onActionName[...]` и писать @/action/name[...]. Идея красивая, попробуем сделать тестовый бранчик feature/actions.

Новые имена методов:  
— `@/action/name[request]` — любой метод
— `@post->/action/name[request]` — только post  
— `@index[request]` — вместо onINDEX
— `@default[request]` — вместо onDEFAULT
— `@notfound[request]` — вместо onNOTFOUND (альтернативы: notFound, not_found)

Для default и index можно сделать алиасы:
— `@/[request]` — index
— `@?[request]` — default
— `@post->index[request]`, `@post->/[request]` 
— `@get->default[request]`, `@get->?[request]`

Для default может быть и не стоит делать разделение на методы. если определен метод `@default[request]`, то пусть туда приходят все запросы, которые мы не смогли обработать, а с методами пусть разбирается программист.

В роутере можно сократить имена хелперов:
— router.assignModule -> router.module  
— router.assignMiddleware -> router.middleware

**Comment by gzzz** [comment]
Я остановился на такой схеме без дополнительных разделителей:
@/[] — index
@method/[] — index

@/path[]
@method/path[]

@?[] — not found
@*[] — default

Вынужденный начальный слеш отлично вписался и двоеточие, в общем-то, лучше не сделает.

**Comment by unhandled-exception** [comment]
* 97e34bb Добавил в контролеры вызов методов по uri. #33

Переключил в pf2-secrets-app котнролеры на новую систему именования экшнов — https://github.com/unhandled-exception/pf2-secrets-app/commit/0eb199bec306243c24c9510647e9f6c848d97aca

Сделал для тестов много имен для служебных экшнов:
— index: index, get->index, /, get->/, onINDEX.
— default: default, DEFAULT, *, onDEFAULT.
— not found: notfound, NOTFOUND, ?, onNOTFOUND.

С именам default и index не нравится, что они могут быть схожи с релаьными урлами: `@index[..]` и `@/index[...]`, `@default[...]` и `@/default[...]`. Различия в коде должны быть более явными. Поэтому не пойдет `@get/action[...]`. Слова index, default, get, post, options часто попадаются в урлах и надо их явно отделять.

Пока думаю, что надо остановиться на INDEX, /, get->INDEX, DEFAULT, NOTFOUND. Звездочка и вопросительный знак мне пока не нравятся совсем.

**Comment by gzzz** [comment]
> Поэтому не пойдет @get/action[...]. Слова index, default, get, post, options часто попадаются в урлах и надо их явно отделять.

Лично я не считаю это проблемой.
Методы явно отделены от пути слешем.

А при создании экшн, всё же, тестируется, после чего, имя слишком часто не меняет.
В крайнем случае можно использовать uppercase-методы.

`@POST/path[]`

Но выглядит несколько кричаще, я попробовал и отказался.

**Comment by unhandled-exception** [comment]
* c348c6a Переименовал pfRouter.assignXXX в pfRouter.XXX.
* c72a7cf Добавил стрелку в вызов процессора: render->ind.pt

**Comment by unhandled-exception** [comment]
> Лично я не считаю это проблемой.
> Методы явно отделены от пути слешем.

Слешами мы отделяем однородные члены в урле. Метод — это не часть урла, поэтому его надо отделать другим знаком. Со стрелкой мы нормально читаем название метода — `@get->/action/test[]` — гет-запрос на /action/test.

**Comment by unhandled-exception** [comment]
> @POST/path[]
Такой вариант имеет право на жизнь, особенно если его писать в стиле http-протокола, с пробелом — `@POST /path[]`. Но стрелка лучше заметна и не путается с любыми компонентами uri.

**Comment by gzzz** [comment]
> Метод — это не часть урла, поэтому его надо отделать другим знаком.

URL начинается со слеша, до него — не URL.
К тому же избавиться от начального слеша мы не можем из-за соображений безопасности и однозначного приведения URL к имени метода. Значит любой разделитель будет избыточным.
Тем более «стрелка».

Если появится поддержка двоеточия в именах методов, то лично я готов подумать над добавлением её в качестве разделителя.
Без этого смысла не вижу и предпочту  более лаконичную схему.

> Такой вариант имеет право на жизнь, особенно если его писать в стиле http-протокола, с пробелом — @POST /path[].

Да. Но только не с пробелом в имени метода — это уж перебор.

**Comment by unhandled-exception** [comment]
От старой системы у нас остались еще post-обработчики — postHTML, postJSON, postAS-IS. 

Можно им тоже придумать новые имена:
— @response<-json[], @response<-html[]
— @json=>response[], @html=>response[]

По такой же схеме можно сделать входящие обработчики:
— @text/json=>request[...]
— @application/xml=>request[]

**Comment by unhandled-exception** [comment]
>  Без этого смысла не вижу и предпочту более лаконичную схему.

Она не лаконичная — разница в один символ не имеет значения. А вот семантика значение имеет. В русском языке мы разделяем разные утверждения точкой, а однородные члены запятой. В названии метода мы разделяем однородные члены запроса слешем, а метод отделяем стрелкой.

**Comment by gzzz** [comment]
> От старой системы у нас остались еще post-обработчики — postHTML, postJSON, postAS-IS.

Да, я уже на них смотрел.
Повинуясь приступу реформаторства сделал, было, так:
`@postXML[result]` → `@~XML[result]`
Но потом вернул взад.

> Можно им тоже придумать новые имена:
> — @response<-json[], @response<-html[]
> — @json=>response[], @html=>response[]

Стрелки коротковаты!
`@response<------------json[]`, `@response<------------html[]` — другое дело!

Лично я (лично я) — против стрелок.
Выглядят они ужасно, будь то C++, PHP или — новая напасть — MySQL.

**Comment by unhandled-exception** [comment]
> Можно им тоже придумать новые имена:
> — @response<-json[], @response<-html[]
> — @json=>response[], @html=>response[]

Нашлось более лаконичное:
— @response<json>[...]
— @request<application/xml>[...]

**Comment by unhandled-exception** [comment]
> Лично я (лично я) — против стрелок.
> Выглядят они ужасно, будь то C++, PHP или — новая напасть — MySQL.

Стрелки ничем не хуже любых других символов — @, _, #, ::, ^, {}, [], (), :=, ->, <-. В Си стрелка -> очень полезная штука, которая разыменовывает указатель и обращается к структуре на которую ссылается указатель. В Го стрелка <- это положить или достать из канала. Все четко и понятно. у нас стрелка показывает какой запрос на какой урл мы обрабатываем. Ничего страшного в любых сокращениях нет, лишь бы они были однозначными.

**Comment by gzzz** [comment]
> В названии метода мы разделяем однородные члены запроса слешем, а метод отделяем стрелкой.

Т. н. стрелка — комбинация минусодефиса и обратной угловой скобки — жуткий гомункул, а не разделитель.
Подходящего разделителя просто нет: дветочие и точку использовать нельзя.
Пробел нагляден, но ему не место в имени метода.
Пайп и восклицательный знак — куда ни шло, но тоже не предел мечтаний.

Если выбирать среди всех вариантов, то я за:
1. @method/path[]
2. @METHOD/path[]

**Comment by unhandled-exception** [comment]
> Т. н. стрелка — комбинация минусодефиса и обратной угловой скобки — жуткий гомункул, а не разделитель.

Это обычный символ, который применяется в куче языков. если тебя смущает вид двух символов, то это решается шрифтами с лигатурами, которые объединяют пары символов в один. Посомтри на https://github.com/tonsky/FiraCode примеры раделителей в разных языках. :)

**Comment by unhandled-exception** [comment]
Жаль, что в Саблайме ФираКод пока не работает. Я сам больше привык к отдельным символам еще со времен ДОСа. :)

**Comment by unhandled-exception** [comment]
Можно доработать подсветку ситаксиса для Саблайма, чтобы она поддерживала подсветку @method->/action[], @response<json>[] и подсвечивала куски названия метода разными цветами.

**Comment by gzzz** [comment]
Это плохой разделитель по комплексу причин.

Во-первых, визуально убогий и чуждый синтаксису Парсера.
Во-вторых — это два символа.
В-третьих — это какие-то ASCII-художества, вместо смысла, a-la emoji-diagram.
В-четвёртых — имена методов с подобным разделителем не выглядят монолитно, их нужно будет заключать в квадратные скобки, что ещё «добавит красоты» всей этой конструкции.

Стрелки — это без меня.

**Comment by gzzz** [comment]
Я предлагаю не торопиться и подождать ответа Константина по префиксам с двоеточием.
Вдруг это легко внедряется.

**Comment by unhandled-exception** [comment]
> Нашлось более лаконичное:
> — `@response<json>[...]`

* 8838c23 Добавил новые имена для post-обработчиков. #33

Переключил pf2-secrets-app на новый вариант пост-обработчика — https://github.com/unhandled-exception/pf2-secrets-app/commit/75873a5d3129316c087f99d70d6bdaf5c67928d8

**Comment by unhandled-exception** [comment]
> В-четвёртых — имена методов с подобным разделителем не выглядят монолитно, их нужно будет заключать в квадратные скобки, что ещё «добавит красоты» всей этой конструкции.

Ничего заключать в скобки не нужно. Отлично работает:
```
@/test[aRequest]
  ^self.method->test[$aRequest]
  ^method->test[$aRequest]
  
@method->test[aRequest]
  Method function.
```

Ручно вызов обработчиков из кода — это крайне редкий шаблон при разаботке. У нас есть экшн и мы для него нашли обработчик. Имя обработчика декларативно и показывает при каких условиях он должен срабатывать. Если нужно явное имя, то всегда можно сделать маршрут с явным именем функции.

Сейчас мы получили примерно то, что делают в современных фреймворках. пример на Го:
```
    r.GET("/ping", func(c *gin.Context) {
        c.JSON(200, gin.H{
            "message": "pong",
        })
    })
```

У нас это теперь выглядит так:
```
@get->/ping[request]
  $result[
     $.type[json]
     $.body[^json:string[$.message[pong]]]
  ]
```

Очень неплохая замена анонимным функциям.

**Comment by gzzz** [comment]
> Ничего заключать в скобки не нужно. Отлично работает

Я не говорил, что оно не работает.
Я сказал «не выглядят монолитно»:
`^self.post/path[]` vs. `^self.post->/path[]`

> @get->/ping[request]

Get вообще нет смысла указывать.

**Comment by unhandled-exception** [comment]
> Get вообще нет смысла указывать.

Стоит из соображений безопасности. Чем уже будут рамки, тем сложнее атакующему.

> Я сказал «не выглядят монолитно»:
> ^self.post/path[] vs. ^self.post->/path[]

Выглядят они одинаково. Только во втором случае понятно, то это запрос на path, а не на /post/path. Допустить ошибку в слеше очень просто, а специально не написать стрелку практически невозможно. 

Мы же не паримся, что нам для вызова метода надо птичку писать. А пишем мы ее, чтобы однозначно отделить вызов от текста. Вот и здесь мы пишем стрелку, чтобы отделить метод от ури.

**Comment by gzzz** [comment]
> Выглядят они одинаково.

Первый вариант выглядит лучше, второй — из двух частей, почти как `^self.post.path[]`

> Мы же не паримся, что нам для вызова метода надо птичку писать. А пишем мы ее, чтобы однозначно отделить вызов от текста. Вот и здесь мы пишем стрелку, чтобы отделить метод от ури.

Я всё это прекрасно понимаю, речь не об отсутствии разделителя, вариант `@path[]` увы невозможен.
Речь о том, что т. н. «стрелка» — плохой разделитель.
И лично я рисовать стрелочки в именах методов не буду.

**Comment by unhandled-exception** [comment]
Двоеточие как разделитель нам не подойдет. ^self.post:/action[...] — это вызов статического метода /action объекта post. А если писать без селфа, то вообще все сломается: ^post:/action[...] — получим, что класс post не определен.

**Comment by gzzz** [comment]
^[post:/path][]

Да, везде квадратные скобки, зато при декларации всё чинно и благородно, с романтикой.

**Comment by unhandled-exception** [comment]
>  Речь о том, что т. н. «стрелка» — плохой разделитель.
Предложи другой вариант. Слеш и двоеточие нам не подходят. Разделитель должен разделять сущности, т.е. он не может быть в составе разделяемых сущностей.

**Comment by gzzz** [comment]
Меня полностью устраивает вариант `@post:/path[]`.
Для больше заметности могу предложить лишь `@POST:/path[]`

Но в целом считаю, что это вопрос привычки.
Я пока пять конроллеров перевёл — допустил несколько ошибок, но под конец прекрасно различал все случаи.

Ну, и судьбы двоеточия нужно подождать.

**Comment by unhandled-exception** [comment]
Ну и понятно, что разделитель должен быть совместим с синтаксисом парсера. Т.е. ^post:/action[] и ^self.post:/action[] не должны делать разные вещи. Программист должен иметь возможность написать вызов метода обычным способом.

**Comment by unhandled-exception** [comment]
>  Я пока пять конроллеров перевёл — допустил несколько ошибок, но под конец прекрасно различал все случаи.

У меня не было ни одной ошибки. Потому что разделитель не допускает путаницы и не требует привыкания.

**Comment by gzzz** [comment]
Я надеюсь, что будет работать `^[post:/path][]` или, быть может, появится другой вариант, скажем, `^{post:/path}[]'.

**Comment by unhandled-exception** [comment]
Должен работать ^post:/path[], иначе это смысла не имеет. Кроме того, двоеточие в Парсере все-таки пространства имен разделяет, а не сущности. Метод и ури — это разные сущности.

**Comment by gzzz** [comment]
> Должен работать ^post:/path[]

Очевидно, что это невозможно.
Такой вызов занят, плюс ему может предшествовать имя статического класса.

> Метод и ури — это разные сущности.

Я не вижу смысла по десятому кругу это обсуждать.
Ты волен делать так, как тебе нравится, я лишь предложил идею.

Благо, я могу использовать свой процессор с удобной мне схемой без стрелок и другой «красоты».

**Comment by unhandled-exception** [comment]
Давай на урл посмотрим — http://username:password@hostname.dm/path/to/action?param1=1&param2=2?tail#part Здесь с семантикой все в порядке. Сущности разделяются разными символами (://, :, @, ?, #), однородные члены одинаковыми (/, ?, &). У нас ровно та же история: сущности разделены стрелкой, однородные члены слешем.

> Ты волен делать так, как тебе нравится, я лишь предложил идею.

Это понятно. Я тебе объясняю логику. Показываю, что эта логика взялась не из воздуха. Вместо логики мы обсуждаем насколько ужасна стрелка, которая применяется в десятках языков. У нас синтаксис Парсера ужасный, а не стрелки. :)

Давай закончим этот спор как бесперспективный. Сейчас есть два более значимых вопроса, что делать с индексом и дефолтами. Я хочу оставить минимальный набор:
— @/[], @get->/[], @INDEX[], @get->INDEX[]
— @DEFAULT[]
— @NOTFOUND[]

**Comment by gzzz** [comment]
> что делать с индексом и дефолтами

Очевидно, что от слеша в начале пути избавиться нельзя.
Значит наиболее логичный вариант для корня — корень: `@/[]`.

`@DEFAULT[]` и `@NOTFOUND[]` пересекаются с методами, что плохо.
И слеши им добавить нельзя, будут похожи на пути, отличаясь только регистром.

`@*[]` и `@?[]` мне нравятся чуть больше, но не верх элегантности.
Пока думаю.

Для постобработки больше всего подходит пайп, он привычен в этой роли:
`@response|json[]`, например.

**Comment by unhandled-exception** [comment]
> Для постобработки больше всего подходит пайп, он привычен в этой роли:
@response|json[], например.

Вариант `@response<json>[...]` взят из синтаксиса шаблонов/дженериков в Си++/Ява. Означает, что это обработчик ответа с типом json. Пайп тоже вариант, но опять мне не нравится, что разделитель очень мелкий. postJSON и response<json> четко отделяет тип, в response|json читается нечетко да еще и можно перепутать с responseIjson и responseljson. Так что пока кажется стоит оставить postJSON и response<json>.

> @DEFAULT[] и @NOTFOUND[] пересекаются с методами, что плохо.
> И слеши им добавить нельзя, будут похожи на пути, отличаясь только регистром.

Методы большими буквами мы не пишем. У нас для методов camelCase. Поэтому если и пересекается, то только с константами. Нам надо показать, что это особенные обработчики. Убрать приставку on логично, поправить в старом коде просто и однозначно.

**Comment by gzzz** [comment]
Можно так, используем капитализацию имён методов и служебных экшнов:
```
@/[] — index
@METHOD/[] — index

@/path[]
@METHOD/path[]

@NOTFOUND[] — not found
@DEFAULT[] — default
```
Читается легко, ничего лишнего, @DEFAULT[] привычен по свойствам и контекстам Парсера.

У постобработчиков убрать приставку post:
```
@XML[]
@JSON[]
```
Лаконично, пересекаться с методами и путями не будет.

**Comment by unhandled-exception** [comment]
Оставил минимальный набор новых экшнов в контролерах, старая схема работает. Новая схема интересная, но надо пробовать в реальных проектах. Подумаю как можно использовать декларативные имена методов в других местах библиотеки. Есть ощущение, что должно хорошо зайти в ОРМ.

Перед тем как вносить любые изменения в маршрутизацию надо написать документацию на контролеры и маршрутизацию. Сделал заготовку docs/controllers.md.

Отредактировал README.md, написал подробнее про установку и простенькоt приложение.

Схема экшнов:
```
     Схему с onXxx, postXXX оствляем, но считаем устаревшей.
     @onActionPath -> @/action/path, @onActionGET -> @get->/on/action
     @onINDEX -> @INDEX, @get->INDEX, @/, @get->/
     @onNOTFOUND -> @NOTFOUND
     @onDEFAULT -> @DEFAULT
     @postJSON -> @response<json>, @postDEFAULT -> @response<DEFAULT>
```

Комиты:
* 6cb9da5 Убрал лишние варианты экшнов, поправил документацию и тесты.
* fa97415 Merge branch 'feature/action' into develop

Влил в develop и master.

**Comment by unhandled-exception** [comment]
* 7a538af Поменял схему вызова экшнов.

Новая схема именования методов в контролере:
```
@/INDEX, @/INDEX<get>, @/, @/<get> — индекс
@/NOTFOUND — обработчик не найден
@/DEFAULT — дефолтный обработчик
@/action/name, @/action/name<post> — экшны
@response<type> — постобработчик вместо postTYPE
@response<*>, @response<DEFAULT> — дефолтный постобработчик вместо
postDEFAULT
```
Сейчас все экшны начинаются со слеша. Обработка ответа `@response<type>`. В угловых скобках во всех случаях указываем шаблон применения метода. Получился простой вариант паттерн-матчинга. 

Потенциально схема с угловыми скобками хорошо расширяется. Пример: `@/settings/users<*,login_required,ajax>[request]` (любой метод, авторизованый, аякс). Без возни со списком методов такое можно сделать только для небольшого числа параметров, иначе получим комбинаторный взрыв и неоднозначность. Но login_required или просто login добавить можно.

**Comment by gzzz** [comment]
Ты этими расширенными опциями будешь пользоваться?

Как подсказывает практика, универсальность прозапас пригождается очень редко, чаще не пригождается вовсе.

**Comment by unhandled-exception** [comment]
> Ты этими расширенными опциями будешь пользоваться?

Я написал, что потенциально можно использовать механизм для патерн-матчинга. Будет ли он востребован не знаю. Сейчас у нас реальное применение только одно — http-методю Понадобится ли авторизация посмотрю на реальном проекте.

Мы получили хорошую систему для экшнов. В коде пишем экшны в виде урлов. Все обработчики четко разделяются. Метод остается в конце как опция и остается безопасно. Есть общая схема для всяких пре- и постпроцессоров (@entity<type>[...]). Главное, что экшны теперь вообще никак не мешаются с методами контролеров. Прямой вызов в коде выглядит органично.

Реализация очень экономичная. Без регулярок и прочих радостей. Посмотрю как пойдет, но скорее всего старую схему имен экшнов можно будет спокойно выпилить через недельку другую.

**Comment by unhandled-exception** [comment]
Я сильно расстроился, что уже 10 лет назад можно было пользоваться навороченными именами методов и классов. При небогатом Парсеровском синтаксисе, можно было наворотить всякого полезного.

**Comment by gzzz** [comment]
Ну, я остановился на https://github.com/unhandled-exception/pf2/issues/33#issuecomment-275713398
Преимущества те же, только без избыточной разметки.

Единственное, что мне не очень нравится — маппинг точки на слеш: будет конфликт адресов /robots.txt и /robots/txt/.
Но случай, скорее, выдуманный, чем реальный. Я расширения использую только для настоящей статики.

> Я сильно расстроился, что уже 10 лет назад можно было пользоваться навороченными именами методов и классов. При небогатом Парсеровском синтаксисе, можно было наворотить всякого полезного.

Это да, но схема-то была вполне удобная.
За исключением редких неоднозначностей и безопасности изменяющих данные методов.

**Comment by unhandled-exception** [comment]
> Ну, я остановился на #33 (comment)
> Преимущества те же, только без избыточной разметки.

Я бы тебе рекомендовал попробовать встроенную в pf2. Она универсальнее. :)

**Comment by gzzz** [comment]
Чем?

**Comment by unhandled-exception** [comment]
Я написал чем. Пользуйся чем хочешь. Это сильно полезно для библиотеки.

**Comment by gzzz** [comment]
Ровно то же самое, только чуть многословнее.
Стрелки, теперь скобки, мне мешают.

Вынести бы имена notfound- и postprocess-методов в поля контроллера.
Это позволило бы не перекрывать @processResponse и @processException.
