### ISSUE TITLE
pfSQLConnection и ROW_COUNT()

### ISSUE THREAD

**Issue by gzzz** [unhandled-exception/pf2#35]
Наблюдаю странную работу ROW_COUNT() — практически всегда возвращает 0.
INSERT иногда даёт не 0, UPDATE и DELETE — всегда.

Нативные методы работают нормально.

```
@auto[]
^use[pf2/lib/sql/connection.p]
$sql[^pfSQLConnection::create[$MAIN:SQL.connect-string]]


@main[]
$db[test_db_^math:uid64[]]

<h1>pf2</h1>
^pf2_connect[]
<h1>native</h1>
^native_connect[]


@pf2_connect[]
^sql.void{CREATE DATABASE $db}
^sql.void{USE $db}

^sql.void{
	CREATE TABLE sessions (
		id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
		user_id INT(10) UNSIGNED NOT NULL,
		PRIMARY KEY (id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8
}

^sql.void{
	INSERT INTO sessions
	(user_id)
	VALUES
	(1)
}

<h2>insert</h2>
^sql.void{BEGIN}
^sql.void{
	INSERT INTO sessions (user_id)
	VALUES (1)
}
row_count: ^sql.int{SELECT ROW_COUNT()}, must be 1
^sql.void{COMMIT}

<h2>update</h2>
^sql.void{
	UPDATE sessions
	SET user_id = 2
	WHERE user_id = 1
}
row_count: ^sql.int{SELECT ROW_COUNT()}, must be 2<br/>
count: ^sql.int{
	SELECT COUNT(*)
	FROM sessions
	WHERE user_id = 2
}

<h2>delete</h2>
^sql.void{
	DELETE FROM sessions
	WHERE user_id = 2
}
row_count: ^sql.int{SELECT ROW_COUNT()}, must be 2<br/>
count: ^sql.int{
	SELECT COUNT(*)
	FROM sessions
	WHERE user_id = 2
}

^sql.void{DROP DATABASE IF EXISTS $db}


@native_connect[]
^connect[$MAIN:SQL.connect-string]{
	^void:sql{CREATE DATABASE $db}
	^void:sql{USE $db}

	^void:sql{
		CREATE TABLE sessions (
			id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
			user_id INT(10) UNSIGNED NOT NULL DEFAULT 0,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8
	}

	^void:sql{
		INSERT INTO sessions
		(user_id)
		VALUES
		(1)
	}

	<h2>insert</h2>
	^void:sql{BEGIN}
	^void:sql{
		INSERT INTO sessions (user_id)
		VALUES (1)
	}
	row_count: ^int:sql{SELECT ROW_COUNT()}, must be 1
	^void:sql{COMMIT}

	<h2>update</h2>
	^void:sql{
		UPDATE sessions
		SET user_id = 2
		WHERE user_id = 1
	}
	row_count: ^int:sql{SELECT ROW_COUNT()}, must be 2<br/>
	count: ^int:sql{
		SELECT COUNT(*)
		FROM sessions
		WHERE user_id = 2
	}

	<h2>delete</h2>
	^void:sql{
		DELETE FROM sessions
		WHERE user_id = 2
	}
	row_count: ^int:sql{SELECT ROW_COUNT()}, must be 2<br/>
	count: ^int:sql{
		SELECT COUNT(*)
		FROM sessions
		WHERE user_id = 2
	}

	^void:sql{DROP DATABASE IF EXISTS $db}
}
```

Результат:
```
pf2

insert
row_count: 0, must be 1

update
row_count: 0, must be 2
count: 2

delete
row_count: 0, must be 2
count: 0

native

insert
row_count: 1, must be 1

update
row_count: 2, must be 2
count: 2

delete
row_count: 2, must be 2
count: 0
```

Лог:
```
Connect	root@localhost on nv using TCP/IP

Query	SET CHARACTER SET utf8
Query	CREATE DATABASE test_db_9C0965D016500CE9
Query	USE test_db_9C0965D016500CE9
Query	CREATE TABLE sessions (
		id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
		user_id INT(10) UNSIGNED NOT NULL DEFAULT 0,
		PRIMARY KEY (id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8
Query	INSERT INTO sessions
	(user_id)
	VALUES
	(1)
Query	BEGIN
Query	INSERT INTO sessions (user_id)
	VALUES (1)
Query	SELECT ROW_COUNT()
Query	COMMIT
Query	UPDATE sessions
	SET user_id = 2
	WHERE user_id = 1
Query	SELECT ROW_COUNT()
Query	SELECT COUNT(*)
	FROM sessions
	WHERE user_id = 2
Query	DELETE FROM sessions
	WHERE user_id = 2
Query	SELECT ROW_COUNT()
Query	SELECT COUNT(*)
	FROM sessions
	WHERE user_id = 2
Query	DROP DATABASE IF EXISTS test_db_9C0965D016500CE9


Query	CREATE DATABASE test_db_9C0965D016500CE9
Query	USE test_db_9C0965D016500CE9
Query	CREATE TABLE sessions (
		id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
		user_id INT(10) UNSIGNED NOT NULL DEFAULT 0,
		PRIMARY KEY (id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8
Query	INSERT INTO sessions
	(user_id)
	VALUES
	(1)
Query	BEGIN
Query	INSERT INTO sessions (user_id)
	VALUES (1)
Query	SELECT ROW_COUNT()
Query	COMMIT
Query	UPDATE sessions
	SET user_id = 2
	WHERE user_id = 1
Query	SELECT ROW_COUNT()
Query	SELECT COUNT(*)
	FROM sessions
	WHERE user_id = 2
Query	DELETE FROM sessions
	WHERE user_id = 2
Query	SELECT ROW_COUNT()
Query	SELECT COUNT(*)
	FROM sessions
	WHERE user_id = 2
Query	DROP DATABASE IF EXISTS test_db_9C0965D016500CE9

Quit	
```

Запросы лога идентичны, ни новых соединений, ни посторонних запросов нет.
Win7x64, Parser 3.4.5, MySQL 5.7.9.

**Comment by unhandled-exception** [comment]
Что ты предлагаешь с этим сделать? Есть идеи по патчу?

**Comment by unhandled-exception** [comment]
Если сделать одинаково, т.е. взять весь метод pf2_connect в ^sql.connect{...}, то все будет работать идентично. Надо смотреть в код Парсера — что и как он вызывает при выходе из оператора connect.

**Comment by unhandled-exception** [comment]
Судя по всему мускуль обнуляет счетчик для row_count() после каждого вызова методов API. А Парсер делает вызов mysql_ping() для каждого закешированного соединения.

```
SQL_Connection* SQL_Driver_manager::get_connection(const String& aurl,
						   Table *protocol2driver_and_client,
						   const char* arequest_charset,
						   const char* adocument_root) {
	// we have table for locating protocol's library
	if(!protocol2driver_and_client)
		throw Exception(PARSER_RUNTIME,
			&aurl,
			"$" MAIN_SQL_NAME ":" MAIN_SQL_DRIVERS_NAME " table must be defined");

	// first trying to get cached connection
	SQL_Connection* connection=get_connection_from_cache(aurl);
	if(connection) {
		connection->set_url();
		if(!connection->ping()) { // we have some cached connection, is it pingable?
			connection->disconnect(); // kill unpingabe=dead connection
			connection=0;
		}
	}
```

И делает это правильно. Поэтому либо оборачивать все блоки с  row_count в connect/transaction. Либо отказаться от такой хрупкой функции в принципе.

**Comment by unhandled-exception** [comment]
Предположение про mysql_ping верное. Смотрим комментарий на https://dev.mysql.com/doc/refman/5.7/en/mysql-ping.html:

> An important thing to keep in mind, especially if you're using threads to keep a database connection open/persistant:
> 
> A call to mysql_ping, even if the connection never went down, will wipe the results of a mysql_affected_rows, if it somehow occurs between a command execution, and the call.
> 
> Symptom: mysql_affected_rows returns -1, when you expect a different number.
> 
> (Note - there could be other reasons, this is just one way to guarantee this behavior.)
>

**Comment by gzzz** [comment]
> А Парсер делает вызов mysql_ping() для каждого закешированного соединения. И делает это правильно.

В рамках парадигмы «всё в одном connect» — пожалуй, но с учётом кэширования connect'ов — странно. Логичнее было бы проверять соединения при попытке им воспользоваться, а не после этого.

**Comment by unhandled-exception** [comment]
Парсер и делает реконект (пинг) при каждом вызове оператора connect. А вот мускулевский драйвер очищает счетчик после пинга.

**Comment by gzzz** [comment]
Напишу в парсерный редмайн, может у Кости будут соображения.

**Comment by unhandled-exception** [comment]
Зачем? В Парсере все правильно сделано. Твоя задача учесть особенность работы rows_count - завернуть пару запросов в connect.

**Comment by gzzz** [comment]
> Твоя задача учесть особенность работы rows_count - завернуть пару запросов в connect.

Да, это решает проблему.

Тогда хоть в комментарии к документации написать.
Тонкий момент, на уровне кэширования вложенных connect'ов.

**Comment by unhandled-exception** [comment]
Это тонкий момент работы Мускуля, который отражен в документации по мускулю. :)

**Comment by gzzz** [comment]
Да, только докопаться до него — дело нетривиальное.
Все работают как документировано, а на выходе слабопредсказуемое поведение.

**Comment by gzzz** [comment]
> An important thing to keep in mind, especially if you're using threads to keep a database connection open/persistant:

> A call to mysql_ping, even if the connection never went down, will wipe the results of a mysql_affected_rows, if it somehow occurs between a command execution, and the call.

> Symptom: mysql_affected_rows returns -1, when you expect a different number.

> (Note - there could be other reasons, this is just one way to guarantee this behavior.)

Забавно, что это не часть документации, а пользовательский комментарий.

**Comment by unhandled-exception** [comment]
Считаем это фичей Парсера. Тикет закрываю.
