### ISSUE TITLE
Точный поиск шаблонов

### ISSUE THREAD

**Issue by unhandled-exception** [unhandled-exception/pf2#40]
Обнаружили некоторую неоднозначность с поиском шаблонов. Можно учитывать префикс шаблона при поиске точно:
* Если шаблон начинается со слеша, то ищем по searchPath, игнорируя basePath.
* Если шаблон начинается с ./ ищем шаблон только от  basePath.
* В остальных случаях ищем сначала в basePath и потом по searchPath.

На первый взгляд несовместимость вылезти не должна.

**Comment by gzzz** [comment]
> На первый взгляд несовместимость вылезти не должна.

Разве что в случаях, когда /file.pt находится рядом, несмотря на «абсолютный» путь.
Но это нелогично и такое лучше поправить в шаблоне.

**Comment by unhandled-exception** [comment]
> когда /file.pt находится рядом
Да, это не совсем хорошая ситуация. У меня, вроде, такого не бывает. Надо будет в отдельной веточке сделать и попробовать.

**Comment by gzzz** [comment]
> Надо будет в отдельной веточке сделать и попробовать.

Проще поискать в шаблонах `^#\s*@(base|import)\s+/.+` и точечно проверить.

**Comment by unhandled-exception** [comment]
6788435 Сделал уточнение поиска шаблона в pfTemplateStorage.find. #18 

* Если aFileName начинается с /, то ищем только по searchPath.
* Если aFileName начинается с ./, то ищем только от aOptions.base.
* В остальных случая ищем сначала от aOptions.base, потом по searchPath.

**Comment by unhandled-exception** [comment]
На моих проектах ничего не сломалось. Леха, если у тебя что-нибудь поломается — маякни, откроем тикет.

**Comment by gzzz** [comment]
Пока ничего не сломалось.
Наблюдаю.
