### ISSUE TITLE
Починить монтирование рутового контролера не в корень сайта

### ISSUE THREAD

**Issue by unhandled-exception** [unhandled-exception/pf2#43]
Алексей попробовал смонтировать «менеджер» в /admin (передал mountTo в конструктор) и получил неработающий контролер. Я попробовал передать в run объект request с отрезанным префиксом в URI и контролер заработал, но не cработал реверс урлов — пути строятся без префикса /admin.

Что хочется получить в результате:
— Делаем реврайт RewriteRule ^/admin /admin/index.html
— В admin/index.html создаем контролер, передаем ему mountTo[/admin] и вызывает run
— run в контролере сам откусывает префикс и настраивает генератор урлов.

**Comment by gzzz** [comment]
Хорошо бы обойтись без рерайта «RewriteRule ^/admin /admin/index.html».
То есть, чтобы монтирование «в корень» работало аналогично существующему монтированию по произвольному пути.

**Comment by unhandled-exception** [comment]
> Хорошо бы обойтись без рерайта

Не совсем понятно как это возможно. Нам же надо привести веб-сервер на какой-нибудь /admin/index.htm в котором инициализировать и запустить совершенно несвязанное с рутовым приложение.

**Comment by unhandled-exception** [comment]
Подумал, что можно будет реврайт сделать в рутовом index.html. Сам проверяешь префикс и инициализируешь либо рутовое, либо админское приложение. Наша задача сделать рабочим mountTo для менеджера и откусывать префикса от полного урла в run.

**Comment by gzzz** [comment]
>> Хорошо бы обойтись без рерайта

> Не совсем понятно как это возможно. Нам же надо привести веб-сервер на какой-нибудь /admin/index.htm в котором инициализировать и запустить совершенно несвязанное с рутовым приложение.

Непонятно я написал. Думал про другое.

Рерайт будет, да.
Префикс отрежет и добавит контроллер.

**Comment by unhandled-exception** [comment]
95e79fa Поправил монтирование рутового контролера не в корень сайта. #43

Чтобы смонтировать приложение не в рут передаем в конструктор контролера `$.mountTo[/admin/modules]` и зовем метод run. Контролер сам отрежет и настроит префикс для dispatch.

**Comment by unhandled-exception** [comment]
95e79fa Поправил монтирование рутового контролера не в корень сайта. #43

**Comment by gzzz** [comment]
А `$self._templatePrefix` не должен устанавливаться в точку монтирования?

Для обычного подмодуля это так и мы в контроллере пишем `^render[template.pt]` и получаем вызов `/module/template.pt`.
А для смонтированного не в корень модуля — нет: префикс у него пустой.

Приходится задавать префикс для смонтированного контроллера вручную.

**Comment by unhandled-exception** [comment]
Рут для шаблонов надо указывать отдельно. Предполагаем, что у нас отдельные приложения, которые лежат в отдельных папках и руты должны быть отдельными. Если у тебя общее приложение, то и монтируй стандартным образом через router.module. Если все отдельно, то и рут задавай отдельно.

**Comment by unhandled-exception** [comment]
> А $self._templatePrefix не должен устанавливаться в точку монтирования?

Задавать надо не templatePrefix, а templateFolder. Указывает он на папку в котором хранятся рутовые шаблоны приложения. Префикс шаблонов будет вычилсятся от templateFolder.

```
$c[^controller::create[
  $.mountTo[/admin]
  $.templateFolder[/../apps/admin/views]
]]
^c.run[]

```

**Comment by gzzz** [comment]
> Задавать надо не templatePrefix, а templateFolder. Указывает он на папку в котором хранятся рутовые шаблоны приложения. Префикс шаблонов будет вычилсятся от templateFolder.

У меня шаблоны отдельного приложения (админки) лежат вместе с остальными, но в директории `admin`.
Потому, `templateFolder` общий, а в контроллере указываю свой `$self._templatePrefix`.

**Comment by unhandled-exception** [comment]
Где лежат шаблоны неважно. Ключевое слово — отдельное приложение. У этого приложения где-то лежат шаблоны. Поэтому мы и указываем папку admin как templateFolder. Лежит admin внутри другой папки с шаблонами или в отдельном месте не имеет значения. Где-то должен существовать рут шаблонов приложения.

Префикс шаблонов существует уже внутри приложения и он на входе в приложение равен "/" и дальше вычисляется исходя из структуры приложения. Поэтому указывать кастомный начальный templatePrefix для обособленного приложения методологически неверно.

Если у тебя шаблоны обособленного приложения начинают использовать шаблоны контейнера, то это уже не обособленное приложение и монтировать его отдельно можно, но не имеет никакого практического смысла.

**Comment by gzzz** [comment]
> Если у тебя шаблоны обособленного приложения начинают использовать шаблоны контейнера, то это уже не обособленное приложение и монтировать его отдельно можно, но не имеет никакого практического смысла.

Шаблоны у меня лежат в такой структуре:
```
views
  admin
    item.pt
    list.pt
  news
    admin
      index.pt
    list.pt
    entry.pt
```

То есть, приложение обособлено (думаю обособить ещё сильнее), во `views/admin` лежат базовые шаблоны админки, от которых наследуются шаблоны админки приложений.

Я не могу указать `/../views/admin` в качестве `templateFolder` — придётся в админ-модуле каждого приложения корректировать путь поиска шаблонов, добавляя `модуль/admin`.
Проще установить `$.templateFolder[/../views/]`, `$self._templatePrefix[admin]` и шаблоны по пути `/../views/news/admin/` будут найдены.

**Comment by unhandled-exception** [comment]
Конкретно в твоем случае придется делать хак с префиксом, поскольку ты смешал шаблоны из разных приложений в одной папке views. Если разложить шаблоны сайта в views/site, а админки в views/admin, то можно обойтись только templateFolder'ом.

Я стараюсь всегда делать еще один уровень в папках app/controllers, app/public, app/views, чтобы можно было делить на «поддомены» (точки монтирования). app/models оставляю без разделения, потому что модель обычно общая, а шаблоны и контролеры радикально отличаются.

Второй вариант — полностью обособленные приложения. Для pf1 есть пример — https://bitbucket.org/ovolchkov/pf-blog/src. Для pf2 у нас есть задача #10 — сделать что-то подобное pfSiteApp из pf1.

Если говорить про хаки с префиксами, то их приходится делать, если у нас какой-то контролер используется несколько раз. Например, у меня есть разные новостные ленты, а я хочу одну админку. Тогда приходится при монтировании модуля в разные токи менять префикс, чтобы не копировать шаблоны.
