### ISSUE TITLE
Передача переменных в шаблоны

### ISSUE THREAD

**Issue by andreyshpigunov** [unhandled-exception/pf2#50]
Предлагаю привести передачу локальных и глобальных к одному виду.
^assignVar[]
^assignVars[]
^template.assign[] -> ^template.assignVar[]
^template.multiAssign[] -> ^template.assignVars[]
Так будет логичнее.

**Comment by unhandled-exception** [comment]
Не будет. assignVar метод контролера, а в контролерах у нас методов с префиксом assign несколько — assignModule, assignMiddleware, assignVar, assignVars. В объекте шаблонизатора у нас другой интерфейс, поэтому используем template.assign, template.multiAssign. Ничего страшного в этом нет. Более того, метод assignVar не вызывает template.assign, поэтому называть их одинаково, значит запутать программиста. 

Для разработчика должно быть тригером — если написал template.assign, значит сделал что-то неправильно. Потому что если мы пишем template.assign, значит нам для чего-то понадобилась глобальная переменная, а это сигнал, что мы что-то делаем неправильно. Из своих примеров я выпилю ^template.assign[siteName;...] :)

**Comment by unhandled-exception** [comment]
Собственно и assignVar в коде не особо нужен. Правильный метод работы с переменными шаблона такой:
— Все общие переменные в контексте контролера задаем, перекрыв метод templateDefaults.
— Локальные в экшне передаем через ^render[template.pt;$.var[...]]
— Для совместимости с pf1 и специфических случаев используем assignVar. (Например, для свойства title).

**Comment by andreyshpigunov** [comment]
Понял, исправлюсь :)
Сейчас использую ^template.assign[] для глобальных переменных, например меню сайта у меня передается в ^template.assign[menu;$core.menu.items]. Его лучше перенести в templateDefaults?

**Comment by unhandled-exception** [comment]
Я с меню поступаю иначе. В корневом контролере (менеджере) делаю хешик mainModules, перекрываю assignModule и наполняю в нем список модулей. А из шаблонов зову его через $ROOT.mainModules. И ничего передавать в шаблон не нужно. :)

**Comment by unhandled-exception** [comment]
Фокус в том, что через переменную ROOT можно добраться до менеджера, а через CONTROLLER дя текущего модуля. Есть даже PARENT, через который можно вообще лезть до упора по иерархии. Раз мы можем добраться до модуля, то можем из него взять и поля, которые нам нужны.

**Comment by andreyshpigunov** [comment]
Ох, я совсем упустил, что PARENT и ROOT тоже доступны в шаблонах.
Спасибо за советы :)
