### ISSUE TITLE
Злонамеренное переопределение полей запроса

### ISSUE THREAD

**Issue by gzzz** [unhandled-exception/pf2#55]
Столкнулся с таким случаем.

В шаблоне страниц есть код:
```
^if(def $self.REQUEST.session){
	… $self.REQUEST.session.sid …
}
```
`$REQUEST.session` устанавливается middleware, который включён только в той части сайта, где требуется аутентификация пользователя — на большинстве страниц `$self.REQUEST.session` пуст.

Злоумышленник делает запрос `/?user_id=1'&id=2'&phpsessid=3'&cookie=4'&page=5'&site=6'&coin=7'&user=8'&userid=9'&pass=10'&password=11'&email=12'&session=13'&api=14'&api_key=15'&expires=16'&expire=17'&date=18'&time=19'&path=20'&php=21'&bit=22'&bitcoin=23'&eth=24'&ethereum=25'&file=26'`, что из-за `@GET_DEFAULT[]` `pfRequest` делает поле `$self.REQUEST.session` определённым, но там не объект сессии, а строка — получаем ошибку «element can not be fetched from string».

Можно, конечно, везде более точно проверять `$self.REQUEST.session`, но я решил вопрос добавив `pfRequest` опцию конструктора `$.protect[]`, где перечисляются те поля, которые могут присутствовать только в `__CONTEXT__` и `@GET_DEFAULT[]` не ищет их в `$form`.

Если решение достаточно концептуально, готов сделать патч.

**Comment by unhandled-exception** [comment]
Давай посмотрим на патч.

**Comment by gzzz** [comment]
https://github.com/unhandled-exception/pf2/compare/master...protected_request_fields?quick_pull=1

**Comment by unhandled-exception** [comment]
Леша, открой сразу PR, чтобы его можно было поревьюить. Если сам открою, то будет странно. :)
