### ISSUE TITLE
В pfSQLSecurity убрать переносы строк при кодировании токенов в base64

### ISSUE THREAD

**Issue by unhandled-exception** [unhandled-exception/pf2#73]
В https://github.com/unhandled-exception/pf2/pull/72 выяснили, что базы данных кодируют base64 по rfc, т.е. добавляют переносы строк после 76 символов в строке.

Для MySQL Андрей Шпигунов применил хотфикс:
```
        $.base64[REPLACE(TO_BASE64(AES_ENCRYPT('{data}', '{key}')), '\n', '')]
```

Надо внести хотфикс для MySQL в pf2. Сделать аналогичную правку для Postgresql.

Пруфы:
— https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_to-base64
— https://www.postgresql.org/docs/13/functions-binarystring.html

-----
План:

- [x] В pfSQLSecurity удалять переносы строк из токенов (возможно сразу все вайтспейсы)
- [x] Написать юниттесты для pfSQLSecurity. Базу поднимаем локально в докерах, пробрасываем реквизиты соединения в тесты через переменные окружения
- [x] Поднять MySQL и Postgres для тестов в actions

**Comment by unhandled-exception** [comment]
@andreyshpigunov вот тут будем чинить токены :)

**Comment by andreyshpigunov** [comment]
Хотфикс для MySQL у меня успешно работает :)

**Comment by unhandled-exception** [comment]
> Хотфикс для MySQL у меня успешно работает :)

Я хочу сделать тесты. Для этого надо научиться поднимать мускуль и постгрес для тестов. Думаю сегодня-завтра дойдут руки до задачи.

**Comment by unhandled-exception** [comment]
@andreyshpigunov Я влил правки и тесты в мастер. Попробуй пожалуйста на своём Майсиквеле. Я пока на боевом Постгресе проверю.

**Comment by unhandled-exception** [comment]
Тесты помогли найти еще одну проблему — в PG в режиме hex мы пытались сериализовать в base64 при encode.

**Comment by unhandled-exception** [comment]
Pr — #75

**Comment by andreyshpigunov** [comment]
Прошу прощения, быстро не смог проверить. Сейчас обновил pf2 в своем движке, все прекрасно работает с MySQL, CSRF ключ однострочный, спасибо :)

**Comment by unhandled-exception** [comment]
Гут
