### ISSUE TITLE
Сериализаторы для pfRequest/pfResponse

### ISSUE THREAD

**Issue by unhandled-exception** [unhandled-exception/pf2#8]
Originally reported by: **Oleg Volchkov (Bitbucket: [ovolchkov](https://bitbucket.org/ovolchkov), GitHub: Unknown)**

----------------------------------------

Алексей Марьин предлагал это сделать для pf1. Возможно имеет смысл добавить методы сериализации в pf2.

Пример:
```
для response сделал так:

serialize:
$lValue[
$.status($aValue.status)
$.type[$aValue.type]
$.contentType[$aValue.contentType]
$.charset[$aValue.charset]
$.headers[$aValue.headers]
$.cookie[$aValue.cookie]
$.body[$aValue.body]
]
$lValue[^json:string[$lValue]]

deserialize:
$lData[^file::load[text;$lCacheFileName]]
$lData[^json:parse[^taint[as-is;$lData.text]]]

$result[^reflection:create[$aType;create;^taint[as-is;$lData.body]][
$.type[$lData.type]
$.status($lData.status)
$.contentType[$lData.contentType]
$.charset[$lData.charset]
]]

$result._headers[$aValue.headers]
$result._cookie[$aValue.cookie]
```

----------------------------------------
- Bitbucket: https://bitbucket.org/ovolchkov/pf2/issue/8

**Comment by unhandled-exception** [comment]
@gzzz а ты нечто подобное в pf2 используешь? :)

**Comment by gzzz** [comment]
Не помню, но раз пример приводил, значит где-то использовал.
Вероятно, для какого-нибудь кэша.
И [исходное обсуждение уже недоступно](https://bitbucket.org/ovolchkov/pf2/issue/8).

Сейчас подобного в коде нет.

**Comment by unhandled-exception** [comment]
Значит ну его куда подальше. Понадобится — сделаем :)
